devices: [0]
pretrained_model_path: null
pretrained_tokenizer_path: null
train_data_path: /train_data/corpus/train
validation_data_path: /train_data/corpus/validation
model_name: model
optimizer: adam
lr_policy: step
lr: 0.0001
lrf: 0.1
l2: 0.0005
clipnorm: 1.0
dropout: 0.0
unk_dropout: 0.0
warm_up: 1000
momentum: 0.9
smoothing: 0.0
rolling_context: 2
embedding_dim: 128
max_conv_filters: 4096
recurrent_units: 1024
reduced_recurrent_units: 64
batch_size: 64
max_q_size: 4096
iterations: 10000
checkpoint_interval: 0
use_gru: false
fix_seed: false
